apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
      - name: test-backend
        image: 553061678476.dkr.ecr.ap-southeast-1.amazonaws.com/backend:dev
        env: 
          - name: DB_TYPE
            value: teethcare-qa
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sapassword
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-qa
spec:
  type: LoadBalancer
  selector:
    app: test-backend
  ports:
  - port: 80
    targetPort: 8080


